In [1]:
import numpy as np
import torch

In [4]:
#create a vector
nv = np.array([[1,2,3,4]])
print(nv), print(" ")

#transpose
print(nv.T), print(" ")

#Transpose again
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]
 
[[1]
 [2]
 [3]
 [4]]
 
[[1 2 3 4]]


In [5]:
#Create a matrix
nM = np.array([[1,2,3,4], [5,6,7,8]])
print(nM), print(" ")

#transpose
print(nM.T), print(" ")

#Transpose again
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
