In [2]:
import numpy as np
import torch

In [4]:
#generate random numbers
np.random.randn(5)

array([-0.17830232, -0.14279614,  0.81942858,  0.29619609, -0.22843352])

In [7]:
#repeat after fixing the seed
np.random.seed(17)
print('Output: ')
print(np.random.randn(5))
print(np.random.randn(5))

# expected output:
# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

Output: 
[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


##New seed mechanism in Numpy

In [3]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

#Expected Output:
# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
#Not seeded value:
# [ 1.1191818  -0.98339611  0.24452002 -0.58140974  0.4295639 ]

print(randseed1.randn(5))
print(randseed2.randn(5))
print(randseed1.randn(5))
print(randseed1.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 2.171257    1.15231025 -1.81881234 -0.13804934  0.53983961]
[ 0.0603312   1.35223028 -0.8003995   1.04143512  0.5320603 ]


##In PyTorch

In [4]:
torch.randn(5)

tensor([ 1.1113, -1.0465,  0.2389,  0.2923, -0.1833])

In [7]:
torch.manual_seed(17)

print('Output: ')
print('Pytorch: ', torch.randn(5))
print('Numpy: ',np.random.randn(5))

Output: 
Pytorch:  tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
Numpy:  [-0.23603363 -0.12361516 -1.57336399 -0.68451016  0.27925055]
