In [2]:
import numpy as np
import torch

In [3]:
#Create random matricies
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

#Successful matricies
print(np.round(A@B, 2)), print(' ')
#The numbers do not match
#print(np.round(A@C, 2)), print(' ')
#Using transpose for valid multiplication
print(np.round( C.T@A, 2))

[[-0.11  1.85 -1.95 -0.59 -0.35]
 [-0.33  0.57 -0.02  1.32  3.33]
 [-0.68  2.12 -2.19  0.33  4.33]]
 
[[ 0.21  1.28 -0.24 -0.6 ]
 [ 0.12 -0.5   0.63  0.76]
 [ 0.09 -0.98  0.22 -0.18]
 [-0.19 -0.32 -0.77 -1.19]
 [ 0.48 -0.74  0.76 -0.05]
 [ 0.61  1.78  1.33  1.74]
 [ 0.31  0.35 -0.31 -1.38]]
