In [1]:
import numpy as np

In [4]:
#create a vector
v = np.array([1, 40, 2, -3])
minval = np.min(v)
maxval = np.max(v)

print('Min, Max: %g,%g' %(minval, maxval))

#with argmin, argmax
minidx = np.argmin(v)
maxdix = np.argmax(v)

#remember the index starts at 0
print('Min, Max: %g,%g' %(minidx, maxdix))

Min, Max: -3,40
Min, Max: 3,1


In [7]:
#with a matrix
M = np.array([[0,1,10],[20,8,5]])

print(M), print(' ')

[[ 0  1 10]
 [20  8  5]]
 


(None, None)

In [11]:
#minimum value
minval1 = np.min(M) #Minimun from entire matrix
minval2 = np.min(M, axis=0) #minimum of each column
minval3 = np.min(M, axis=1) #minimum for each row

print(minval1)
print(minval2)
print(minval3)

0
[0 1 5]
[0 5]


In [12]:
#minimum index
minidx1 = np.argmin(M) #Minimun from entire matrix
minidx2 = np.argmin(M, axis=0) #minimum of each column
minidx3 = np.argmin(M, axis=1) #minimum for each row

print(minidx1)
print(minidx2)
print(minidx3)

0
[0 0 1]
[0 2]
